### ISSUE TITLE
 virtal dressing master-while  am using  your code i have attached  facing this issue and please help me issue in this concerns

### ISSUE THREAD

**Issue by satya-71** [MRishiK99/VirtualDresser#1]
![Screenshot from 2020-08-19 18-28-38](https://user-im
![Screenshot from 2020-08-19 18-28-38](https://user-images.githubusercontent.com/50202310/90637963-4d444b00-e24a-11ea-9c36-2f7a814ab5dd.png)
ages.githubusercontent.com/50202310/90637697-f2aaef00-e249-11ea-9efa-fa5bd88a26d8.png)

**Comment by MRishiK99** [comment]
Requires that file in your local
