### ISSUE TITLE
Please update version of  installtion dependencies  like mxnet and glunocv

### ISSUE THREAD

**Issue by satya-71** [MRishiK99/VirtualDresser#2]

**Comment by MRishiK99** [comment]
I had compatibility issues while using recent versions. You can try branching out from this repo and try changing the versions.

**Comment by satya-71** [comment]
> _No description provided._

yeah i have tried so many versions dependencies but unable to get the result due to due to mxnet.please give me som hints abou what exactly i required to install?

**Comment by MRishiK99** [comment]
please refer mxnet documentation
